name: air-quality
services:
  ui:
    build:          # "where is the Dockerfile location?"
      context: .    # in root directory
      dockerfile: ./docker/ui/Dockerfile
    image: indraps30/ui_aq  # Docker_Hub_Username/Docker_Image_Name
    container_name: frontend_aq
    depends_on:
      - api         # UI service only run after API service.
    ports:
      - "8501:8501" # Host:Container

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: indraps30/api_aq
    container_name: backend_aq
    ports:
      - "8080:8080"