columns_datetime:
- tanggal
columns_int:
- pm10
- pm25
- so2
- co
- o3
- no2
- max
columns_object:
- stasiun
- critical
- category
features:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
impute_co: 11.0
impute_no2: 18.0
impute_o3: 29.0
impute_pm10:
  BAIK: 28.359154929577464
  TIDAK BAIK: 55.17809298660362
impute_pm25:
  BAIK: 39.827586206896555
  TIDAK BAIK: 82.38564668769716
impute_so2: 35.306404657933044
label: category
label_categories:
- BAIK
- SEDANG
- TIDAK SEHAT
label_categories_new:
- BAIK
- TIDAK BAIK
path_clean_ros:
- ../data/processed/X_ros.pkl
- ../data/processed/y_ros.pkl
path_clean_rus:
- ../data/processed/X_rus.pkl
- ../data/processed/y_rus.pkl
path_clean_sm:
- ../data/processed/X_sm.pkl
- ../data/processed/y_sm.pkl
path_clean_test:
- ../data/processed/X_test_feng.pkl
- ../data/processed/y_test_feng.pkl
path_clean_valid:
- ../data/processed/X_valid_feng.pkl
- ../data/processed/y_valid_feng.pkl
path_data_joined: ../data/interim/joined_dataset.pkl
path_data_raw: ../data/raw/
path_data_test:
- ../data/interim/X_test.pkl
- ../data/interim/y_test.pkl
path_data_train:
- ../data/interim/X_train.pkl
- ../data/interim/y_train.pkl
path_data_valid:
- ../data/interim/X_valid.pkl
- ../data/interim/y_valid.pkl
path_data_validated: ../data/interim/validated_data.pkl
path_fitted_encoder: ../models/ohe_stasiun.pkl
path_fitted_scaler: ../models/scaler.pkl
range_co:
- -1
- 47
range_no2:
- -1
- 65
range_o3:
- -1
- 151
range_pm10:
- -1
- 179
range_pm25:
- -1
- 174
range_so2:
- -1
- 82
range_stasiun:
- DKI1 (Bunderan HI)
- DKI2 (Kelapa Gading)
- DKI3 (Jagakarsa)
- DKI4 (Lubang Buaya)
- DKI5 (Kebon Jeruk) Jakarta Barat
