name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker Compose Build and Push
      run: |
        docker compose build
        docker compose push
  
  docker-pull-ec2:
    needs: docker-compose-build
    runs-on: ubuntu-latest
    steps:
    - name: Creating SSH Configuration File
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deployment.pem
        chmod 600 ~/.ssh/deployment.pem
        cat >> ~/.ssh/config <<END
        Host deploy_ec2
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deployment.pem
          StrictHostKeyChecking no
        END
    - name: Deploy to EC2
      run: |
        ssh deploy_ec2 "rm -rf docker-compose.yaml"
        ssh deploy_ec2 "wget https://raw.githubusercontent.com/indraps30/mlp-aq2026/refs/heads/master/docker-compose.yaml"
        ssh deploy_ec2 "sudo docker compose pull && sudo docker compose up -d"
